### ISSUE TITLE
Add leading and trailing parameters to debounce and throttle

### ISSUE THREAD

**Issue by maxlapides** [dart-lang/stream_transform#100]
It is sometimes helpful to specify whether a debounced stream should invoke on the leading or trailing edge of the timeout.

For example, right now we're working on a feature where the user can flip through weekly charts. We want to debounce API calls because the user can flip very quickly, and we don't need to make API calls for charts that the user has effectively skipped. It would be nice to be able to specify that we want to invoke on the leading edge to support the common use case where the user flips back only one week, and expects that chart to load instantly.

For reference, JavaScript's lodash has implemented these parameters:

- [debounce](https://lodash.com/docs/#debounce)
- [throttle](https://lodash.com/docs/#throttle)

**Comment by natebosch** [comment]
I had a hard time making decisions about this. I've seen the API with the argument in a few places and always felt it was harder to use and understand what it would do.

In the use described I don't think `debounce`, but emit right away, is the semantics we'd want.

Debounce trailing:
```
a-b-c----d-e-f---
-------a--------d
```

Debounce leading:
```
a-b-c----d-e-f---
a--------d-------
```

Desired:

```
a-b-c----d-e-f---
a------c-d------f
```

If I understand correctly we want to react to the first click, then wait until there have not been clicks for some duration, then react to the last click. Is that right?


I wonder if `buffer` has semantics closer to what you want? The way I think about it is "I'll use the trigger to tell you when I'm ready for values.". By sending a trigger immediately, you'd express that the first event that comes through is handled. Then you can wait to send another trigger until you are ready to react to another event.


```dart
var clicks = someStreamOfClicks();
var trigger = StreamController<void>()..add(null); // ready right away for first event.
clicks.buffer(trigger.stream).listen((c) {
  loadChart(c.last);
  // wait at least 1 second before loading another chart.
  Future.delayed(const Duration(seconds: 1), () {
    trigger.add(null);
  });
});
```

**Comment by maxlapides** [comment]
Thanks for the quick response @natebosch! That code snippet is very helpful, and I think it will solve the problem we have. We'll give it a shot!

I recently switched from mostly writing JavaScript to mostly writing Dart, and in my experience I found the `leading` and `trailing` parameters generally useful in lodash. I think that having sensible defaults for these parameters is the trick, so users don't need to fully grasp the intricacies to make use of `debounce` and `throttle`. I do see the argument for keeping it simple, though!

**Comment by natebosch** [comment]
It also occurred to me over the weekend that we have [`asyncMapBuffer`](https://pub.dev/documentation/stream_transform/latest/stream_transform/AsyncMap/asyncMapBuffer.html) for pretty much exactly this use case:

```dart
someStreamOfClicks()
  .asyncMapBuffer((c) async {
    await loadChart(c.last);
    // wait at least 1 second before loading another chart.
    await Future.delayed(const Duration(seconds: 1));
  })
  .drain();
```

**Comment by maxlapides** [comment]
Ah that's really cool. Thanks for the code sample!

**Comment by maxlapides** [comment]
Hey @natebosch I'm just testing out your recommendation! It seems like using `asyncMapBuffer` has slightly different behavior than what we're hoping for. Using the code you provided, it looks like this:

```
a-b-c-d-e-f-g-h-i-j--
a---b---d---f---h---j
```

But ideally what we want is debounce behavior:

```
a-b-c-d-e-f-g-h-i-j--
a-------------------j
```

^ This is currently how `.debounce` works, except it doesn't emit the leading `a`.

**Comment by natebosch** [comment]
Yeah if you do want to wait specifically for an amount of time between clicks instead of strictly limiting the number of calls per period of time we'd need different semantics.

I'm worried that the semantics desired here are sufficiently different from `debounce` that we shouldn't try to overload that name by using some other arguments. If we can find a nice enough name for these semantics specifically I think we could add a new operator.

Do you have any thoughts on naming? Do we feel like these semantics are likely to come up as useful for multiple projects?

**Comment by maxlapides** [comment]
I do think that this kind of thing is likely to come up as useful in general. My background is in web application engineering, and I've done a bunch of projects over the years where I ended up using lodash's debounce and throttle methods and have found the `leading` and `trailing` parameters to be helpful. Perhaps I'm just used to how these parameters work and having them available, so I'm biased towards matching lodash's implementation by adding these parameters. I'm not sure what the alternative would be, but I will think about it and if I think of anything clever I'll be back here :)

**Comment by natebosch** [comment]
Ah, I see what makes this difficult in particular. The lodash `debounce` has different semantics even without the leading or trailing options passed. The implementation here always emits the _first_ element at the end of the series of events, whereas lodash uses the _last_ argument it saw when it calls the debounced function.

It looks like rx also emits the _last_ even always. That is probably the semantics most folks would expect, but I'm not sure how breaking it would be to change it now. If we do change that I think it does get easier to add these optional arguments.

So what we have by default is:

```
a-b-c----d-e-f---
-------a--------d
```

What we want by default is:

```
a-b-c----d-e-f---
-------c--------f
```

That would be equivalent to `leading: false, trailing: true.

**Comment by natebosch** [comment]
oof, and looking closer we _do_ have the behavior we'd want, but my documentation is lying 😳 


This may be feasible to implement.

**Comment by maxlapides** [comment]
I was confused, but now I see what you mean: the documentation is incorrect right now. PR #101 makes perfect sense to me. Thanks!

**Comment by maxlapides** [comment]
Nice! Thanks so much!
