### ISSUE TITLE
Recommendations on "closable" transformed streams?

### ISSUE THREAD

**Issue by enetor** [dart-lang/stream_transform#117]
This is not a bug. Rather, I am seeking recommendations from the experts :-)

Normally we listen to a broadcast Stream with a StreamSubscription. When we are done processing events from that stream, we clean up by closing the StreamSubscription.

There is no easy way to clean up a transformed stream. For example:

`
final outputStream = stream1.combineLatest(stream2, combinerFn);
`

According to the API, `outputStream` won't be closed until both `stream1` and `stream2` are closed. In reality, however, we may want to close `outputStream` and clean up the internal StreamSubscriptions, so `combinerFn` won't fire any more. But we do not want to close `stream1` or `stream2` - they may be owned by third-party libraries, or they are still serving other parts of the app.

We have internal customers who have a large number of stream transformations and are concerned about the wasted memory and CPU cycles.

Before rolling our own combineLatest solution that supports proper cleanups, I would like to understand if this is the right way to go. Or is it something that can be resolved within package:stream_transform?

Thanks!

**Comment by natebosch** [comment]
The confusion here is over terminology. When the docs say "The result stream will not close until both the source stream and other have closed." it is meant from the stream _producer_ side. It relates to when the `onDone` callback of the stream listener will be invoked.

The term we use for what you are describing is not for a stream to be closed, but for a listener to be canceled.

Listener canceling should be wired up correctly. If you cancel your subscription (or all subscriptions in the case of a broadcast stream) then the listeners on the source streams will be canceled as well. If you have a reproduction case where you see a listener that isn't being canceled and should I'll be happy to take a look.
