### ISSUE TITLE
Audit should cancel timer when done

### ISSUE THREAD

**Issue by tomgilder** [dart-lang/stream_transform#142]
Hello, the [audit method](https://github.com/dart-lang/stream_transform/blob/master/lib/src/rate_limit.dart#L201) should call `timer.cancel()` in `onDone`. This is causing my Flutter widget tests to fail due to pending timers that haven't been cleaned up.

**Comment by tomgilder** [comment]
Oh, sorry, I guess it can't due to nature of the method - needs to keep the timer alive to output any remaining events - is that right? Feel free to close if so 😁

**Comment by natebosch** [comment]
Yes, this behavior of the timer living beyond the end of the stream is to keep the invariant that there will be _at least_ `duration` in between events on the output stream.
