### ISSUE TITLE
Are you interested in collaboration?

### ISSUE THREAD

**Issue by brianegan** [dart-lang/stream_transform#16]
Hey hey :) The RxDart project actually has a layer of about 30 StreamTransformers. It would be quite simple to massage our transformers to fit into this library's style. Our transformers are pretty well tested by this point through a few rounds of feedback, and we could easily migrate those as well to fit this libs style. Also, each transformer has decent DartDocs included.

Anyhow, if you're up for a bit of collaboration, let us know!

Update, totally failed to paste a link: https://github.com/ReactiveX/rxdart/tree/master/lib/src/transformers

**Comment by matanlurey** [comment]
Hi @brianegan!

I think at first look we would definitely be interested in merging/collaborating. I'd like to get @natebosch's input, since he's driving the package right now.

/cc @kevmoo

**Comment by kwalrath** [comment]
Just for the record, it looks like these are the StreamTransformer docs: https://www.dartdocs.org/documentation/rxdart/latest/rx_transformers/rx_transformers-library.html#classes

**Comment by kevmoo** [comment]
@natebosch is out of the office until August (a new addition to his family).

We'll need to find an engineer on our side to handle pull requests/reviews.

**Comment by natebosch** [comment]
There is a lot of overlap so collaboration sounds like a great idea. Taking a brief look at the library it looks like there may be a bit of an impedance mismatch that could make it a little tough - rx_transformers exposes utilities as classes and stream_transform doesn't.

While I'm out if @matanlurey or someone else has bandwidth to work on this I went ahead and wrote up my [hopes for this package](https://github.com/dart-lang/stream_transform/blob/5d5176603da7659439b57ee2e488940ba45abe97/package_vision.md) - these are intended as more of a placeholder for the reviews I might give than an obligation to handcuff the repo.

I'm really excited to see how this goes!

**Comment by brianegan** [comment]
Cool, I'll open up a couple small PRs and we can see how it goes. Thanks for providing the vision doc! From the RX side, any transformers you wouldn't want here to can happily remain in our repo. We want to play well within the Dart community, so collaboration on the most useful transformers would be grand :)

"Taking a brief look at the library it looks like there may be a bit of an impedance mismatch that could make it a little tough - rx_transformers exposes utilities as classes and stream_transform doesn't."

Yep, but this would be a super quick change for us actually. The class structure we have is just syntactic sugar around an internal factory function. We could simply unwrap and expose the factory function instead of the class itself. It would actually simplify the implementation! I think we just went for classes as we thought it was a bit more idiomatic as many Dart peeps seem to favor OO over functional construction, but turns out that might be the wrong gut feeling.
