### ISSUE TITLE
Angular tests time out when using transformers from this package

### ISSUE THREAD

**Issue by chalin** [dart-lang/stream_transform#18]
### Context

The [toh-6](https://github.com/angular-examples/toh-6) example AngularDart app has [angular_test-based tests](https://github.com/angular-examples/toh-6/tree/master/test) that run fine under Dart 1.23 and 1.24-dev.

### Migration from [stream_transformers](https://pub.dartlang.org/packages/stream_transformers)

We recently switched out use of the [stream_transformers](https://pub.dartlang.org/packages/stream_transformers) package and used this one instead (because this package is strong mode compliant) -- cf. https://github.com/dart-lang/site-webdev/pull/719. Switching to this package was relatively straighforward:

[stream_transformers](https://pub.dartlang.org/packages/stream_transformers) transformer | this package
--- | ---
`new Debounce(...)` | `debounce(...)`
`new FlatMapLatest(...)` | `switchMap(...)`

### Hero search

One of the app features is a hero search which lists matching hero names as the user types, like this:
<img src="https://webdev.dartlang.org/resources/images/devguide/toh/toh-hero-search.png">

The hero search feature is explained in the AngularDart tutorial [part 6, section on Streams](https://webdev.dartlang.org/angular/tutorial/toh-pt6#streams).

### Hero search tests

Some test checks if search box heroes-found list is appropriately updated as search text is progressively typed; e.g. [this test](https://github.com/angular-examples/toh-6/blob/master/test/hero_search.dart#L82-L85):
```dart
test('list heroes matching ${searchText}g', () async {
    await _typeSearchTextAndRefreshPO('g');
    expect(await po.heroNames, ['Magneta', 'Magma']);
  });

...

Future _typeSearchTextAndRefreshPO(String searchText) async {
  await po.search.type(searchText);
  Stream<List> herosStream;
  await fixture.update((c) => herosStream = c.heroes);
  // Wait for the data to be fetched from db. ...
  await herosStream.first; // <***********************************************
  po = await fixture.resolvePageObject(HeroSearchPO);
}
```

As shown above in the `_typeSearchTextAndRefreshPO()` method, to test this feature, w/o having to wait for a fixed amount of time, the [angular_test waits on the hero search result stream at this line](https://github.com/angular-examples/toh-6/blob/master/test/hero_search.dart#L101) -- marked with `<****` above.

While this test works fine when using the transformers from [stream_transformers](https://pub.dartlang.org/packages/stream_transformers), it fails (due to a timeout waiting on the stream) when using the transformers from this package. 

cc @kwalrath @kevmoo 

Cf. https://github.com/dart-lang/site-webdev/pull/719#discussion_r121031304

**Comment by natebosch** [comment]
This looks like it's exposing a bug in the test. `c.heroes` is a broadcast Stream so we can't guarantee the event has not already fired before the `await herosStream.first;` can add it's listener. The reason this was working in the old version is that the `await herosStream.first` happens to hit before the `debounce` has finished and the even gets emitted.

I can get the same timeout by either omitting the debounce or adding `await new Future.delayed(const Duration(milliseconds: 400));` before `await herosStream.first;` to make sure we're not waiting until after the debounce lets the event through.

That said - I'd still like to understand why the behavior is different in this implementation...

**Comment by natebosch** [comment]
Somewhere in `package:stream_transformers` the Stream is getting listened to early which 'hooks up' the Debounce and lets it catch the event that gets missed in the `package:stream_transform` version. I think in this test the `await herosStream.first` should be the only listener AFAICT, but I see the original stream's listen getting called before we get there.

IMO the behavior of this package is correct - if you debounce a broadcast Stream we should drop events that happen before the first listener.

**Comment by natebosch** [comment]
Hmm, I take that back - something else is going on.

**Comment by natebosch** [comment]
Ah - yeah this `debounce` has a bug. I think the test also has a bug, but it should work because the listener is added elsewhere, not by `package:stream_transformers` and shouldn't be impacted by the StreamTransformer here.

There is a bug where `debounce` only delivers the value to one of the listeners when there is a broadcast stream.

**Comment by chalin** [comment]
> There is a bug where debounce only delivers the value to one of the listeners when there is a broadcast stream.

Oh! Good catch! Nasty situation to debug. (Sounds like there'll be a need for some extra tests to ensure that transformers don't break broadcastedness :)

**Comment by natebosch** [comment]
We definitely have this bug in other transformers in this package, I think fixing it in debounce is enough to solve the immediate issue.

Since we will see this pretty much everywhere we use `new StreamTransformer.fromHandlers` I think it'll end up being cheaper to reimplement that with the semantics I thought it had than to change all the usages to other patterns. I've got a PR out doing just that, assuming it looks good I'll audit the rest of the transformers in this package for the same issue.

**Comment by natebosch** [comment]
Hmm, test still times out with a path override to the version with this fix.

**Comment by natebosch** [comment]
Tracked this down to an unfortunate interaction between `debounce` and the test framework.

It seems that the `await po.search.type(searchText);` will wait for any `Timer` instances that are started during the input change handler. `package:stream_transform` uses a `Timer` in `debounce` where `package:stream_transformers` uses `new Stream.periodic`.

I can see the test framework waiting for the Timer if I add one inside `search(String term)` on `HeroSearchComponent` - it must be using a zone to hook in to these.

We can get around this by getting the listener on the Stream before typing so we're sure we don't miss an event even if the test framework doesn't finish the future until it fires.

```dart
Future _typeSearchTextAndRefreshPO(String searchText) async {
  Future firstHero;
  await fixture.update((c) => firstHero = c.heroes.first);
  await po.search.type(searchText);
  await firstHero;
  po = await fixture.resolvePageObject(HeroSearchPO);
}
```
