### ISSUE TITLE
Implement `merge` and `mergeAll`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/stream_transform#4]
Reference: http://reactivex.io/documentation/operators/merge.html.

**Comment by matanlurey** [comment]
Actually, it's not clear this would be a transformer.

**Comment by natebosch** [comment]
If we wanted to implement this as a StreamTransformer I think we could.

`someStream.transform(merge(someOtherStream))`

It looks like there are two variants in Rx. A static `Observable.merge(source1, source2)` and a method on observable instances. You can see both versions here: http://www.introtorx.com/Content/v1.0.10621.0/12_CombiningSequences.html#Merge

I think the `transform(merge(someOtherStream))` implementation fits this package. I think the other approach wouldn't.
