### ISSUE TITLE
`scan` like transform with different output

### ISSUE THREAD

**Issue by tp** [dart-lang/stream_transform#66]
Hi,

this might be more of a question / clarification instead of a feature request.

I had the following task to solve, and only came up with a very cumbersome solution using multiple (data leaking) transforms, and either I have overlooked something, or there is really a place for a new transform.

The basic premise is this: I have an end-less scroll view that emits the last viewed item's index. And I have an API where I can load pages of 10 items each.

My approach is then, whenever the `viewItemIndex` Sink is pushed to, to calculate the next page after that item, and then retrieve all pages between the last loaded page and the desired one.

The last step (using `max()`-like logic and expanding the single input to a stream of pages to load) is what makes my current implementation a little cumbersome (I use scan to save the previously loaded index, and then that state gets passed to an `asyncExpand` that emits loads from `previous` to `current` page index).

I think a better API for this case (and all cases where one wants a little bit of encapsulated, private state in order to produce the next result) would be something I dub `scanExpand` here (just using expand here for the biggest version, people could of course also only return 1 item).

```dart
    _lastViewedProductIndex.stream
        .map(pageFromIndex)
        .transform(scan(0 /* highest loaded page */,
            (int highestLoadedPage, int nextDesiredPage) sync* /* returns Stream<int> */ {
                for (var highestLoadedPage = nextDesiredPage; i <= highestLoadedPage; i++) {
                    yield i;
                }

                return nextDesiredPage; // Not how to best type this in Dart, what we need would maybe be an Result object with `nextState` and `stream` property
          }
        ).asyncMap(loadPage);
```

I hope I made my use-case clear. Do you see the value in this, or would something similar already be possible with existing constructs?

Thanks for any input you have :)!

**Comment by natebosch** [comment]
I'm not entirely sure I follow what `scanExpand` is meant to do - your example wouldn't work because a `sync*` method can't return a value.

FWIW I do think it's fairly idiomatic to store local state in and capture it in a closure.


```dart
int highestLoadedPage = 0;
_lastViewedProductIndex.stream
    .map(pageFromIndex)
    .expand((page) sync* {
      if (page > highestLoaded) {
        highestLoaded = page;
        yield* Iterable.generate(highestLoaded - page, (i) => i + page);
      }
    }).asyncMap(loadPage);
```

If you do want to avoid keeping this state outside of the Stream values I think the idea of a class that has both the `highestLoadedPage` and an `Iterable<int>` for the pages that need to be loaded would make sense.


Does that answer your question?

**Comment by tp** [comment]
Hi @natebosch,

indeed keeping the state outside of the stream makes it much simpler, I just though that wasn't how to do it.

As for my example, I know that Dart doesn't allow `yield` + `return` (and additionally with different types), so I though in the end this would need to return a generic class `Result<S, T>(S nextState, Stream<T> values)` or something similar. (The issue with my current approach is that I return an object, which then gets used as the next state as well as the input for the next sta**g**e / operator, which thus gets some internal data that I wouldn't want to expose.

That would be my same objection to the code above, it's easily visible which functions access `highestLoadedPage` (were they all defined inline). But I guess that could also be remedied by having a function like `expandToHighest`, so I wouldn't define that inline.

Thanks for your input so far, I'll take these thoughts all into consideration and see if there is already a simple solution without any new features. :)

**Comment by natebosch** [comment]
Yeah I think if you wanted to avoid closing over state from the surrounding code the right thing to do would be to add a class yourself that captures the 2 things you want and have your `scan` call translate into that object type, then `map` or `expand` back to the thing you're after. The `Result` class in this case is probably too specialized to put here.
