### ISSUE TITLE
Error: Map literal requires exactly two type arguments

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/stream_transform#71]
Dart version: 2.1.0

Error:
```
Failed to precompile build_runner:build_runner:
file:///home/ubuntu/.pub-cache/hosted/pub.dartlang.org/stream_transform-0.0.16/lib/src/combine_latest_all.dart:69:31: Error: Map literal requires exactly two type arguments.
      final hasEmitted = <int>{};
                              ^^
```
caused by this line - https://github.com/dart-lang/stream_transform/blob/master/lib/src/combine_latest_all.dart#L69

**Comment by jumperchen** [comment]
FYI: From the code usage of `hasEmitted.add()` and `hasEmitted.contains()`, I think you were using `List` instead of `Map`.

**Comment by natebosch** [comment]
oops!

the issue here is we forgot to bump up the minimum version of the SDK when we started using set literals

**Comment by janosroden** [comment]
Hi, our CI build is broken too, but we got a different error:

```
stream_transform-0.0.16/lib/src/combine_latest_all.dart:69:31: Error: Set literals are not supported yet.
      final hasEmitted = <int>{};
```

When can you release a fix, @natebosch ?

**Comment by natebosch** [comment]
This should be solved now with a `pub upgrade`. Version `0.0.16+1` does not use a set literal.

**Comment by janosroden** [comment]
Works again, thanks!
