### ISSUE TITLE
Library documentation is empty

### ISSUE THREAD

**Issue by nex3** [dart-lang/stream_transform#89]
The dartdoc.org documentation for this library displays no documentation at all: https://pub.dev/documentation/stream_transform/1.0.0/stream_transform/stream_transform-library.html

**Comment by natebosch** [comment]
Caused by https://github.com/dart-lang/dartdoc/issues/2032

Should be resolved once the pub site upgrades to a new enough dartdoc.

I was unsure about publishing before the pub site worked, in the end I decided it wasn't worth waiting.

**Comment by natebosch** [comment]
Fixed with the latest version of the pub site.
