### ISSUE TITLE
stream_transform with flutter

### ISSUE THREAD

**Issue by willladislaw** [dart-lang/stream_transform#93]
The current Dart SDK version is 2.6.0-dev.0.0.flutter-1103600280.

Because conn_demo depends on stream_transform >=0.0.20 which requires SDK version >=2.6.0 <3.0.0, version solving failed.
pub get failed (1)

**Comment by natebosch** [comment]
You'll need to either:

- Switch to the dev channel on flutter which has a newer Dart SDK.
- Wait until the stable channel of flutter has a newer Dart SDK.
- Use version `0.0.19` until the Flutter SDK is upgraded to the newer Dart SDK.

The SDK constraints are working as expected here.
